# Generated by Django 3.0.6 on 2020-09-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0002_auto_20200921_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(to='Empleado.Habilidades'),
        ),
    ]
