# Generated by Django 3.1.2 on 2020-10-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0004_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_nam',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'Titular'), ('1', 'Rotar en plantilla'), ('2', 'Esporadico'), ('3', 'Otro')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
