# Generated by Django 3.1.2 on 2020-10-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0005_auto_20201010_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['id'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
    ]
