# Generated by Django 3.1.2 on 2020-10-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0007_auto_20201018_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
    ]
